"""Write docs/report.md from a stored run. Every number is computed here from the saved answers;
a difference is called a finding only when the two 95% Wilson ranges do not overlap.

  uv run python scripts/write_report.py --run 2
"""

import argparse
import json
import sys
from collections import Counter, defaultdict
from itertools import combinations

from shelfradar.analyzer import DomainClassifier, wilson
from shelfradar.api import DB_PATH, STUDY_DIR
from shelfradar.config import PROJECT_ROOT
from shelfradar.factcheck import load_fact_sheet
from shelfradar.models import Engine, Status
from shelfradar.orchestrator import load_study
from shelfradar.report import analyze_all, build_report
from shelfradar.store import Store

ENGINE = {"ai_overview": "Google AI Overview", "ai_mode": "Google AI Mode", "copilot": "Bing Copilot"}
VARIANT = {"mumbai-en": "English (Mumbai)", "delhi-hi": "Hindi (Delhi)", "delhi-hinglish": "Hinglish (Delhi)"}
CLASS = {"other": "review blogs and other sites", "marketplace": "shops", "brand": "brands' own websites",
         "media": "news media", "ugc": "Reddit/YouTube/Quora/Instagram", "search_engine": "Google/Bing pages"}


def pct(x: float) -> str:
    return f"{x:.0%}"


def rng(row: dict) -> str:
    return f"{pct(row['rate'])} ({pct(row['low'])}–{pct(row['high'])}, {row['named']}/{row['answered']})"


def separated(a: dict, b: dict) -> bool:
    return a["high"] < b["low"] or b["high"] < a["low"]


def group_differences(rows: list[dict], brands: list[str], label: dict) -> list[str]:
    by = defaultdict(dict)
    for r in rows:
        by[r["brand"]][r["group"]] = r
    out = []
    for brand in brands:
        groups = by.get(brand, {})
        for g1, g2 in combinations(sorted(groups), 2):
            a, b = groups[g1], groups[g2]
            if separated(a, b):
                hi, lo = (a, b) if a["rate"] > b["rate"] else (b, a)
                out.append(f"- **{brand}**: {label[hi['group']]} {rng(hi)} vs {label[lo['group']]} {rng(lo)}")
    return out


def table(rows: list[dict], brands: list[str], groups: list[str], label: dict) -> list[str]:
    by = {(r["brand"], r["group"]): r for r in rows}
    head = "| Brand | " + " | ".join(label[g] for g in groups) + " |"
    lines = [head, "|---|" + "---|" * len(groups)]
    for b in brands:
        cells = [f"{pct(by[(b, g)]['rate'])} ({pct(by[(b, g)]['low'])}–{pct(by[(b, g)]['high'])})"
                 if (b, g) in by else "0%" for g in groups]
        lines.append(f"| {b} | " + " | ".join(cells) + " |")
    return lines


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", type=int, required=True)
    ap.add_argument("--focus", default="MuscleBlaze")
    args = ap.parse_args()

    store = Store(DB_PATH)
    run = store.get_run(args.run)
    study = load_study(STUDY_DIR / "whey.json")
    domains = DomainClassifier.load(study.brands, STUDY_DIR / "domain_classes.json")
    answers = store.answers(args.run)
    rep = build_report(answers, study, domains, args.focus, factcheck=store.factcheck(args.run),
                       fact_sheet=load_fact_sheet(STUDY_DIR / "facts.json"))
    analyses = analyze_all(answers, study, domains)
    questions = json.loads((STUDY_DIR / "questions.json").read_text(encoding="utf-8"))["questions"]

    top = [r["brand"] for r in rep["overall"]][:8]
    answered = [a for a in analyses if a.answered]

    # Dice
    dice = rep["dice"]
    changed = sum(not d["identical"] for d in dice)
    ch_low, ch_high = wilson(changed, len(dice))

    # Sources
    classes = rep["source_classes"]
    total_sources = sum(classes.values())
    translated_by = Counter()
    sources_by = Counter()
    for a in answered:
        key = (a.answer.engine.value, a.answer.variant)
        translated_by[key] += a.translated_sources
        sources_by[key] += len(a.answer.sources)
    hindi_titles = Counter(a.answer.engine.value for a in answered if a.answer.variant == "delhi-hi"
                           for src in a.answer.sources if any("\u0900" <= ch <= "\u097f" for ch in src.title))
    no_block = Counter(a.answer.variant for a in analyses if a.answer.status is Status.NO_AI_BLOCK)
    aio_cells = Counter(a.answer.variant for a in analyses if a.answer.engine is Engine.AI_OVERVIEW)

    first = sorted(rep["first_mention"].items(), key=lambda kv: -kv[1])
    o = rep["outside_top10"]
    fc = rep["factcheck"]

    L = [
        "# ShelfRadar study: who do AI search engines recommend for whey protein in India?",
        "",
        f"_Run {run['id']} · recorded {run['created_at'][:10]} · {run['live_calls']} SerpApi searches · "
        f"generated by `scripts/write_report.py` from the saved answers_",
        "",
        "## Setup",
        f"- **Questions:** {len(questions)} real buying questions found through Google autocomplete and "
        "People Also Ask (`study/questions.json`), each in English, Hindi and Hinglish.",
        "- **Engines (all via SerpApi):** Google AI Overview (`google` + `google_ai_overview` follow-up), "
        "Google AI Mode (`google_ai_mode`), Bing Copilot (`bing_copilot`).",
        "- **Where:** English from Mumbai, Hindi and Hinglish from Delhi (`location`, `gl=in`, `hl`). "
        "Copilot takes only the question text.",
        f"- **Repeats:** every cell asked {max(a.answer.sample for a in analyses) + 1} times with `no_cache=true`.",
        f"- **Answers:** {rep['answers']} cells · {rep['status'].get('ok', 0)} with an AI answer · "
        f"{rep['status'].get('no_ai_block', 0)} where Google showed none · {rep['status'].get('error', 0)} errors.",
        f"- **Brands tracked:** {len(study.brands)} (`study/whey.json`).",
        "- **Statistics:** every share has a 95% Wilson range. A difference is reported as a finding only when "
        "the two ranges do not overlap; otherwise it is a tie.",
        "",
        "## Findings",
        "",
        "### 1. The same question rarely gets the same brand list twice",
        f"In **{changed} of {len(dice)}** repeated pairs (same question, engine and language, asked again with "
        f"no cache) the set of brands named changed: {pct(changed / len(dice))} "
        f"(95% range {pct(ch_low)}–{pct(ch_high)}). A one-shot \"AI ranking\" is not a stable number; "
        "visibility has to be measured as a probability. This matches SparkToro and Gumshoe's 2026 study, "
        "which found AI brand lists repeat less than 1% of the time.",
        "",
        "### 2. Overall visibility (share of AI answers naming the brand)",
        *table(rep["overall"], top, ["all"], {"all": f"All engines and languages (n={len(answered)})"}),
        "",
        "Tiers (brands whose ranges overlap the tier leader share its tier): "
        + "; ".join(f"tier {t}: " + ", ".join(r["brand"] for r in rep["overall"] if r["tier"] == t)
                    for t in sorted({r["tier"] for r in rep["overall"]})[:3]) + ".",
        "",
        "### 3. Being named most is not the same as being named first",
        "Brand named first in the answer: "
        + ", ".join(f"{b} {n}" for b, n in first[:5]) + f" (of {len(answered)} answers).",
        "",
        "### 4. Engines disagree about Indian D2C brands",
        *table(rep["by_engine"], top, ["ai_overview", "ai_mode", "copilot"], ENGINE),
        "",
        "Differences whose ranges do not overlap:",
        *(group_differences(rep["by_engine"], top, ENGINE) or ["- none"]),
        "",
        "### 5. Language: English vs Hindi vs Hinglish",
        *table(rep["by_variant"], top, list(VARIANT), VARIANT),
        "",
        "Differences whose ranges do not overlap:",
        *(group_differences(rep["by_variant"], top, VARIANT)
          or ["- none at this sample size: every language gap shown above is within the ranges (a tie)."]),
        "",
        "### 6. Where AI Overview gets its sources",
        f"- {pct(o['outside_by_url'])} of {o['sources']} AI Overview sources are not among the top-10 organic "
        f"results for the same search (by page; {pct(o['outside_by_domain'])} by website). "
        "For comparison, Ahrefs (March 2026, US) found 38% of AI Overview citations in the top 10, "
        "i.e. 62% outside.",
        "- Source types across all engines: "
        + ", ".join(f"{CLASS.get(k, k)} {n} ({pct(n / total_sources)})"
                    for k, n in sorted(classes.items(), key=lambda kv: -kv[1]))
        + ". Shops and review blogs are cited far more than brands' own websites.",
        "",
        "### 7. Google answers Hindi questions from machine-translated English pages",
        "Share of cited sources that were English pages served through Google Translate:",
        "",
        "| Engine | English | Hindi | Hinglish |",
        "|---|---|---|---|",
        *[f"| {ENGINE[e]} | " + " | ".join(
            f"{translated_by[(e, v)]}/{sources_by[(e, v)]}"
            + (f" ({pct(translated_by[(e, v)] / sources_by[(e, v)])})" if sources_by[(e, v)] else "")
            for v in VARIANT) + " |" for e in ENGINE],
        "",
        "Google's AI Overview and AI Mode cite translated English pages for Hindi and Hinglish questions. "
        f"Bing Copilot cites none: for Hindi questions {hindi_titles['copilot']}/{sources_by[('copilot', 'delhi-hi')]} "
        "of its sources have Hindi (Devanagari) titles, i.e. it reads Hindi-language sites. "
        "Caveat: sources within one answer are not independent, so read these as counts, not as a precise rate.",
        "",
        "### 8. When Google shows no AI answer",
        "AI Overview missing, by language: "
        + ", ".join(f"{VARIANT[v]} {no_block[v]}/{aio_cells[v]}" for v in VARIANT)
        + ". Too few cases to call it a pattern.",
        "",
        f"### 9. Sites to win for {args.focus} (citation gap)",
        f"Websites the AI cited in answers that named a rival but not {args.focus}:",
        *[f"- {g['domain']} ({g['class']}): {g['answers']} answers" for g in rep["citation_gap"][:8]],
        "",
        "### 10. Recommended or just listed (Gemini reading, every quote verified)",
    ]
    if fc.get("available"):
        L += [
            f"Read {fc['answers_read']} answers ({fc['models_note'] or fc['model']}); "
            f"{fc['dropped_by_verification']} items dropped by plain-code checks ("
            + ", ".join(f"{n} {reason}" for reason, n in fc["dropped_reasons"].items()) + ").",
            "",
            "| Brand | Recommended | Neutral | Warned against |",
            "|---|---|---|---|",
            *[f"| {s['brand']} | {s['recommended']} | {s['neutral']} | {s['negative']} |" for s in fc["stance"][:8]],
            "",
            "Conflicting product facts between answers:",
            *([f"- [{c['severity']}] {c['brand']} {c['product']}: {c['attribute'].replace('_', ' ')} "
               f"stated as {' vs '.join(c['values'])}" for c in fc["conflicts"]] or ["- none"]),
        ]
    else:
        L.append("Not run for this run yet.")

    L += [
        "",
        "## Accuracy of the brand counting",
        "See [eval.md](eval.md): a human checked 30 answers (precision 100%, 0 false alarms); a coverage audit "
        "found brands missing from the list, which were added before this report was generated.",
        "",
        "## Limits",
        "- One category (whey protein), five questions, two repeats per cell: a pilot, not a census. "
        "Ranges are wide for smaller brands.",
        "- One city per language; Copilot is not localised.",
        "- AI answers change over time; this is a snapshot of the recording date.",
        "- The stance reading is by an LLM; quotes are verified, but recommended vs neutral is a judgement. "
        "Brands added after the reading have no stance yet unless the fact-check was re-run.",
        "- Mentions inside cited page titles do not count; only the AI's own words.",
        "",
        "## Sources referenced",
        "- SparkToro & Gumshoe, AI recommendation consistency study (2026), reported by Search Engine Land: "
        "https://searchengineland.com/ai-recommendation-lists-rarely-repeat-study-468076",
        "- Summary of AI Overview citation vs ranking studies (Ahrefs, BrightEdge, seoClarity, Originality.AI): "
        "https://apiserpent.com/blog/ai-overview-citations-vs-rankings-overlap",
    ]
    out = PROJECT_ROOT / "docs" / "report.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))
    return 0


if __name__ == "__main__":
    sys.exit(main())
